#+TITLE: org-latex-instant-preview
=Org-latex-instant-preview= provides instant preview of LaTeX snippets via MathJax outputed SVG. Unlike [[https://github.com/fuxialexander/emacs-webkit-katex-render][webkit-katex-render]], this does not need xwidget support.
* Dependencies
  - [[https://github.com/Malabarba/names][Names]]
  - [[https://github.com/mathjax/MathJax-node][MathJax-node]]
  - [[https://github.com/mathjax/mathjax-node-cli/][MathJax-node-cli]]
  - [[https://github.com/tumashu/posframe][posframe]]

* Installation
  You can install =MathJax-node-cli= via ~npm~:
  #+BEGIN_SRC shell
npm install mathjax-node-cli
  #+END_SRC
  You need to set ~org-latex-instant-preview-tex2svg-bin~ to the location of the executable ~tex2svg~.

* Usage
  #+BEGIN_SRC emacs-lisp
(use-package org-latex-instant-preview
  :defer t
  :init
  (setq org-latex-instant-preview-tex2svg-bin
        ;; location of tex2svg executable
        "~/node_modules/mathjax-node-cli/bin/tex2svg"))
  #+END_SRC

** Start Instant Preview
   Put your cursur in some LaTeX fragment or some math environments, and invoke
   #+BEGIN_SRC emacs-lisp
(org-latex-instant-preview-send-latex)
   #+END_SRC
   When you make modifications, an instant preview will be regenerated when Emacs is idle for ~org-latex-instant-preview-delay~ seconds.

** Stop Instant Preview
   #+BEGIN_SRC emacs-lisp
(org-latex-instant-preview-stop)
   #+END_SRC

* Customization

** Delay Time Before Re-compilation
   Custom ~org-latex-instant-preview-delay~ to change the number of seconds to wait before re-compilation after Emacs is idle.

** Location of ~tex2svg~ Executable
   ~org-latex-instant-preview-tex2svg-bin~

* License
  This piece work is licensed under UNLICENSE.
